### PR TITLE
ISSUE-337: Personal Boards

### LINKED ISSUE #337: Create Personal Boards
- All students have one Personal Board per project
- Each board is visible by only the one student and their teacher (teachers will have a dashboard for viewing students' personal boards -- maybe this looks similar to the current project boards dashboard)
- Teachers can set one background image that applies to all students' personal boards for that project
- Like any other board, students can create, edit, move, tag, upvote, etc. posts

For students the Personal Board may be accessed from an icon in the nav bar of any board in the project (perhaps displayed in a pop-up window)

For teachers, there may be a Personal Boards card in the project boards dashboard that opens up a nested Personal Boards dashboard. The Personal Boards dashboard shows each of the students' name as separate boards that can be opened. The settings control in the Personal Boards dashboard can be used to edit the board configurations for all personal boards.

### LINKED ISSUE #339: Add Teacher-only Join Codes
This issue was inspired after working on adding personal boards to projects.

We need to update our project schema to not only be restricted to 1 teacher. We should allow adding multiple teachers to each project. This will also require us to create a new join code specifically for teachers to use. Only teachers will be able to use this new join code to join as a teacher on a project.

### PR DESCRIPTION
**Pull request by Ammar-T**
#### Adds support for personal boards and shared boards.
- Personal Teacher Boards (Only visible to teachers)
- Personal Student Boards (Only visible to teachers and the specific student)
- Shared Boards (Visible to all students and teachers)

#### Creation of personal boards is a toggle-able setting viewable in the "Create Project" modal. 
- If disabled, there will be no personal boards.
- If enabled, personal boards will be created whenever someone joins a project.

#### Added Teacher-only invite codes to projects.
- Now, multiple teachers can be assigned to a single project.
- Teachers will join through an exclusive code, which is different from the student join code.
- Currently, teacher accounts can only join as teachers. Students can only join as students.

NOTE: There's a lot of breaking changes, so no previous projects/boards are still usable. If there are any that need to be "recovered", let me know and I'll look into it. I'll also create a new issue to introduce database migrations.

Closes #337 
Closes #339

### CODE REVIEW

**Comment by JoelWiebe** [comment]
Teacher Personal Boards:
- I might go back a bit on what I had mentioned previously, what do you think about all teachers having their own personal boards afterall?
- As currently implemented, all teachers can see the personal boards of all students and all teachers -- but students can only see their own personal board
- When teachers edit the board configurations and click "Update Configuration" a confirmation dialogue will say something like "Board configurations will be updated for all students' and teachers' personal boards. Would you like to continue?"
- For the nav bar on teachers' personal boards, should we hide (1) workspace, (2) workflow, (3) buckets, and (4) groups -- as we aren't using these at this time

Students' Personal Boards
- For the nav bar on students' personal boards, should we hide from students the (1) workspace and (2) buckets icons for the time being? 
- Should we show the settings icon to the teachers though, so that teachers can change the board configurations from any board

Teacher Project Dashboard:
- Can we separate the personal boards into "Student Personal Boards" and "Teacher Personal Boards"
- Could we order the boards as (1) "Shared Project Boards", (2) "Student Personal Boards, then (3) "Teacher Personal Boards" (ordered from top to bottom)

**Comment by Ammar-T** [comment]
@JoelWiebe 

> I might go back a bit on what I had mentioned previously, what do you think about all teachers having their own personal boards afterall?

This is already the case (each teacher gets own personal board), unless you're saying that all teachers get 1 combined shared board?

> As currently implemented, all teachers can see the personal boards of all students and all teachers -- but students can only see their own personal board

This is the current logic as well. Teachers see everything, while students only see their own personal board.

> When teachers edit the board configurations and click "Update Configuration" a confirmation dialogue will say something like "Board configurations will be updated for all students' and teachers' personal boards. Would you like to continue?"

What if instead we add a checkbox option before they submit saying "Apply configuration to all personal boards?" This is just to keep some flexibility in the case where teachers don't want one board config change to affect all other boards. 

> For the nav bar on teachers' personal boards, should we hide (1) workspace, (2) workflow, (3) buckets, and (4) groups -- as we aren't using these at this time

Yep, I'll add this change.

> For the nav bar on students' personal boards, should we hide from students the (1) workspace and (2) buckets icons for the time being?

Will do.

> Should we show the settings icon to the teachers though, so that teachers can change the board configurations from any board

Agree, will add.

> Can we separate the personal boards into "Student Personal Boards" and "Teacher Personal Boards"

This would be nicer, I'll change it.

> Could we order the boards as (1) "Shared Project Boards", (2) "Student Personal Boards, then (3) "Teacher Personal Boards" (ordered from top to bottom)

Agree with showing shared boards first, I'll change it.

**Comment by JoelWiebe** [comment]
@Ammar-T I like your suggestions! 

Yes, in terms of teachers having their own boards, exactly like it is now--I hadn't thought of that but once I saw it, that makes sense :)

In terms of the options for applying configuration settings, do you think we could have two sets of options, e.g.,
For student personal boards:
"Apply configuration to all STUDENT personal boards?"
"Apply configuration to all STUDENT and TEACHER personal boards?"

For teacher personal boards:
"Apply configuration to all TEACHER personal boards?"
"Apply configuration to all STUDENT and TEACHER personal boards?"

(This could allow students and teachers to have different backgrounds and purposes for their personal boards)

**Comment by JoelWiebe** [comment]
Really excited to try out all these new features! 

@Ammar-T would you mind helping me out by merging the latest develop branch into this PR so I can try this out with the grouping tool? No rush--whenever you get a chance :)

**Comment by LunarFang416** [comment]
> Really excited to try out all these new features!
> 
> @Ammar-T would you mind helping me out by merging the latest develop branch into this PR so I can try this out with the grouping tool? No rush--whenever you get a chance :)

Once your checkout to this branch, you can just do `git pull origin develop` and it will merge the develop branch into the personal board branch.

**Comment by JoelWiebe** [comment]
> > Really excited to try out all these new features!
> > @Ammar-T would you mind helping me out by merging the latest develop branch into this PR so I can try this out with the grouping tool? No rush--whenever you get a chance :)
> 
> @JoelWiebe Once you're checkout to this branch, you can just do `git pull origin develop` and it will merge the develop branch into the personal board branch.

@Ammar-T Oh, perfect! Thanks for the pro tip :)

**Comment by Ammar-T** [comment]
@JoelWiebe Did the merge work? 

I wonder if there were conflicts which would be hard to fix without the person who wrote the code for this branch.

If there were conflicts, let me know and I can do the merge and push.

**Comment by JoelWiebe** [comment]
@Ammar-T @LunarFang416 Sorry, it was actually the task-ui PR that I was having difficulties merging with the develop branch (https://github.com/encorelab/ck-board/pull/346). 

There are a bunch of merge conflicts on that one, could I get your help with that when you have a chance?

**Comment by Ammar-T** [comment]
@JoelWiebe Fixed the merge conflicts in here.

**Comment by JoelWiebe** [comment]
> @JoelWiebe
> 
> > I might go back a bit on what I had mentioned previously, what do you think about all teachers having their own personal boards afterall?
> 
> This is already the case (each teacher gets own personal board), unless you're saying that all teachers get 1 combined shared board?
> 
> > As currently implemented, all teachers can see the personal boards of all students and all teachers -- but students can only see their own personal board
> 
> This is the current logic as well. Teachers see everything, while students only see their own personal board.
> 
> > When teachers edit the board configurations and click "Update Configuration" a confirmation dialogue will say something like "Board configurations will be updated for all students' and teachers' personal boards. Would you like to continue?"
> 
> What if instead we add a checkbox option before they submit saying "Apply configuration to all personal boards?" This is just to keep some flexibility in the case where teachers don't want one board config change to affect all other boards.
> 
> > For the nav bar on teachers' personal boards, should we hide (1) workspace, (2) workflow, (3) buckets, and (4) groups -- as we aren't using these at this time
> 
> Yep, I'll add this change.
> 
> > For the nav bar on students' personal boards, should we hide from students the (1) workspace and (2) buckets icons for the time being?
> 
> Will do.
> 
> > Should we show the settings icon to the teachers though, so that teachers can change the board configurations from any board
> 
> Agree, will add.
> 
> > Can we separate the personal boards into "Student Personal Boards" and "Teacher Personal Boards"
> 
> This would be nicer, I'll change it.
> 
> > Could we order the boards as (1) "Shared Project Boards", (2) "Student Personal Boards, then (3) "Teacher Personal Boards" (ordered from top to bottom)
> 
> Agree with showing shared boards first, I'll change it.

@Ammar-T Will you still have time to implement these before the our September launch?

**Comment by Ammar-T** [comment]
@JoelWiebe Oh I forgot to push those additions. I was able to re-order the cards and hide some of the nav bar icons. 

I need to update the configuration modal to apply all changes and then it should be done.

The re-ordering and hidden icons don't really need testing since it's straightforward but I'll ping you once I update the config modal.

**Comment by JoelWiebe** [comment]
> @Ammar-T I like your suggestions!
> 
> Yes, in terms of teachers having their own boards, exactly like it is now--I hadn't thought of that but once I saw it, that makes sense :)
> 
> In terms of the options for applying configuration settings, do you think we could have two sets of options, e.g., For student personal boards: "Apply configuration to all STUDENT personal boards?" "Apply configuration to all STUDENT and TEACHER personal boards?"
> 
> For teacher personal boards: "Apply configuration to all TEACHER personal boards?" "Apply configuration to all STUDENT and TEACHER personal boards?"
> 
> (This could allow students and teachers to have different backgrounds and purposes for their personal boards)

@Ammar-T Regarding the points above, maybe we could simplify this so that the teacher personal board changes can only have the option to apply to ALL teacher personal boards and (2) student personal boards can only have the option to apply to ALL student personal boards

P.S. Sorry about the confusion with merging--obviously I didn't get enough sleep and was making some silly mistakes, haha

**Review by JoelWiebe — APPROVED** [review]
(Please ignore this comment... posted in the wrong PR)

**Review by LunarFang416 — APPROVED** [review]
LGTM!!!

**Review by JoelWiebe — CHANGES_REQUESTED** [review]
Just waiting for a ping from @Ammar-T when latest requested changes are merged :)

**Comment by Ammar-T** [comment]
> @Ammar-T Now on hotspot and the connection is working perfectly, haha.
> 
> Can you check out my project as a teacher **(on the staging DB cluster)**, join code: HZNFC
> 
> For some reason the personal boards are not being created, I should have:
> 
> * One teacher personal board and
> * One student personal board

@JoelWiebe The reason they weren't created was because when you created that project, you didn't enable the setting that creates personal boards when users join. You would need to create a new project with that setting enabled.

Screen Shot 2022-09-07 at 9 48 51 PM

**Comment by Ammar-T** [comment]
@JoelWiebe Added all the changes/fixes. Feel free to test again and I can check out anything if needed. 

I'll be merging this into branch `RUN-Sept-08-2022` which will be pointing to our staging server temporarily. It includes a clean copy of `develop` plus the additions of personal boards from this branch once merged.

**Comment by JoelWiebe** [comment]
@Ammar-T 🤦‍♂️ It must have been that there were still personal board sections in the dashboard but they were empty that through me off. My bad. That makes sense!

Thanks for getting this done. You're a life saver!

**Pull request merged**
