### PR TITLE
Create Embeddable URLS

### LINKED ISSUE #455: Remove student from a project
From the Project modal pop-up's Membership tab, allow teachers to remove students

### LINKED ISSUE #465: Make Workspace, Learner Model, Personal Board, and TODO tool embeddable
The following apply only to teacher UIs and should NOT be viewable by any students
1. Add the "file copy" icon to every community canvas (tooltip: "Copy embeddable URL") <- [UPDATED]

- [ ] Remove the copy embeddable URL button from the board configurations and 
Screen Shot 2022-12-28 at 8 14 26 PM

- [ ] Add a "file copy" icon next to the task description icon in the top left of every community board

Screen Shot 2022-12-28 at 8 08 15 PM

2. Add a generic personal board embeddable URL copy icon to each personal board

- [ ] As for community boards, also add the "file copy" icon next to the task description of every personal board
- [ ] However, the embeddable URL should be generic (e.g., /project/[project ID]/my-personal-board)?embedded=true) such that a user's request would return their personal board for that project (/projejct/[project ID]/board/[board ID])
- [ ] Design a means of directing each user to their own personal board when they request the generic personal board URL (i.e., as described above /project/[project ID]/my-personal-board would direct each user to that user's own personal board for that project: /projejct/[project ID]/board/[board ID])
- [ ] If the "embedded" parameter equals "true", then remove the nav bar and all back or home buttons such that the user cannot navigate away from the current page (as already done with the community board embed links)

3. Add the embeddable URL icon to each workspace
Screen Shot 2022-12-28 at 8 27 41 PM

- [ ] Add the file copy icon next to the workspace title in the top left of the nav bar (e.g., /project/04a0c298-92d5-44af-bc09-2b6dbb880692/workspace?embedded=true)
- [ ] If embedded is set to true, the workspace should be returned without the nav bar (as already done with the board embed links)
- [ ] If the "embedded" parameter equals "true", then remove the nav bar and all back or home buttons such that the user cannot navigate away from the current page (as already done with the board embed links)

4. Add the embeddable URL icon to the CK Monitor page
- [ ] Add the file copy icon next to the CK Monitor title in the top left of the nav bar (e.g., /project/04a0c298-92d5-44af-bc09-2b6dbb880692/monitor?embedded=true)
- [ ] If embedded is set to true, the learner model should be returned without the nav bar (as already done with the board embed links)
- [ ] NOTE: Keep in mind that currently only the teacher uses the CK Monitor but in the future when students access this URL they should be presented with only the contents of their own learner model -- and not be able to see the task completion or user models of other students (this will be a separate issue)
- [ ] If the "embedded" parameter equals "true", then remove the nav bar and all back or home buttons such that the user cannot navigate away from the current page (as already done with the board embed links)

5. Make a TODO tool page with its own URL and embeddable URL

- [ ] Transition the TODO tool from a modal pop-up to its own page 
- [ ] Add the file copy icon next to the TODO title in the top left of the nav bar (e.g., /project/04a0c298-92d5-44af-bc09-2b6dbb880692/todo?embedded=true)
- [ ] If embedded is set to true, the workspace should be returned without the nav bar (as already done with the board embed links)

### PR DESCRIPTION
**Pull request by LunarFang416**
## Details

- Embeddable URLs created for CK Workspace, CK Monitor, personal boards and todo lists
- Embeddable URLs do not show navbar and cannot be navigated to any other page
- Todo Modal is now a separate page, teacher view includes TODO Lists for all students, and students will only see their own todo lists (same behaviour for the embeddable URLs)

- Also implemented user deletion from project

Closes #465, Closes #455

### CODE REVIEW

**Comment by JoelWiebe** [comment]
@LunarFang416 Everything works great!! Wonderful work on this.

In terms of the title, sorry I didn't specify clearly, would it be possible to have the title displayed in an absolute position on the canvas -- like the back button (see image below)

Screen Shot 2023-01-16 at 5 49 53 PM

The following styling could be used on the div containing the text (like the Back button)

`    padding: 0.6em;
    position: absolute;
    top: 0.5em;
    left: 0.5em;
    font-weight: bold;
    background-color: white;
    color: #6c63ff;
    border-radius: 0.5em;
    font-size: 1em;`

**Comment by JoelWiebe** [comment]
@LunarFang416 Is there anything you believe would require approval from another developer, or could we merge this immediately after you make the above change?

**Comment by JoelWiebe** [comment]
@LunarFang416, would you mind resolving conflicts and wrapping up this feature? I'm hoping to start testing in classrooms within the next week or two.

**Comment by LunarFang416** [comment]
@JoelWiebe Fixed the board name and conflicts!

**Review by JoelWiebe — APPROVED** [review]

**Pull request merged**
