### PR TITLE
ISSUE-361: Lock Project Membership Setting

### LINKED ISSUE #361: Create Lock Project Membership Toggle
As SSO (for the time being) removes board access restrictions, can we create a slide toggle in the Membership tab of the Project Configurations? Perhaps this toggle can be added just above the Invite Code.
Screen Shot 2022-09-04 at 12 21 23 AM

### PR DESCRIPTION
**Pull request by Ammar-T**
## Details

- Adds ability to lock project membership which restricts anyone from joining a project
- Updated SSO code to check if membership if locked before adding new users to prevent potential security issues

## Unrelated addition
- For invite codes, I changed them to buttons so if you click them, it'll copy the invite code to your clipboard

Closes #361

### CODE REVIEW

**Review by JoelWiebe — CHANGES_REQUESTED** [review]
Thanks for making quick work of this!!

Successful tests:
 - successfully locked out student invite code
 - successfully locked out teacher invite code
 - successfully created a new project with restricted access to new members

Changes requested:
 1. An error occurred when creating a project with no lock on membership (see Figure 1)
 2. Could we (a) add the word "Copy" for the two invite codes (e.g., Copy Student Invite Codes; Copy Teacher Invite Codes) and (b) remove the period from the locking membership checkbox option?
 3. Users with SCORE accounts are still automatically added to the project membership if they navigate to the URL of any board (e.g., http://localhost:4201/project/07894b0a-eaca-4338-bf4e-07301cc9c752/board/54246da9-8f3b-4bc9-a921-dadb601106ab) -- NOTE: To test this I was running SCORE locally

**Figure 1. Error when creating new project with no locked membership**
Screen Shot 2022-09-11 at 4 13 21 PM

Let me know if you have any questions for me!

**Comment by Ammar-T** [comment]
@JoelWiebe Thanks for catching those bugs! The new commit should have fixed everything mentioned above. If joining the project via SCORE bug still exists, I'll try setting up SCORE locally and testing it out myself so I don't bother you after every commit lol.

**Review by JoelWiebe — APPROVED** [review]
Brilliant. All looks good to me! (I guess no need to setup SCORE locally just yet, haha)

**Review by LunarFang416 — APPROVED** [review]
LGTM

**Pull request merged**
