### PR TITLE
feat/18_allow-hyperlinks

### LINKED ISSUE #18: Allow hyperlinks in post descriptions
Links should pop out in a new tab.

### PR DESCRIPTION
**Pull request by StevenWuzz**
Allow hyperlinks in a post's message
## Details
- URLs are detected and converted with https://
- Links can only be opened in a new tab

Closes #18

### CODE REVIEW

**Comment by StevenWuzz** [comment]
NB: I haven't tested whether the hyperlink is still enabled after editing since I don't have an access to do that operation

**Review by Ammar-T — APPROVED** [review]

**Comment by JoelWiebe** [comment]
I'm not sure why I'm getting this error when I run ng serve

image

**Comment by Ammar-T** [comment]
@JoelWiebe Steven added a new dependency in this PR (`linkifyjs`) which requires you to run `npm install` (adds this dependency into your local version of the application).

Then try `ng serve` and it should work.

**Comment by JoelWiebe** [comment]
@Ammar-T, oh my goodness, of course! Thanks

**Review by JoelWiebe — CHANGES_REQUESTED** [review]
Looks great!

Tested:
- add website with https to title
- add website with https to message
- add website with http to body
- add website starting with www to body
- edited message body with existing hyperlinked content

The title did not become a hyperlink, but this is fine -- probably best that links be in body anyway. Most other tests passed, however, I noticed that if I add a link (e.g. https://joelwiebe.ca add save it, then open it up to edit then save again, all html tags and attributes are shown both on the board and in the modal pop up)
image

Is there an easy way that when we open the note to edit, the hyperlink is displayed just as plain text again (e.g., "https://joelwiebe.ca") -- or someway of preventing the html from being displayed when we are editing a note?

**Comment by StevenWuzz** [comment]
That's pretty weird. I've made sure that was not supposed to happen. Maybe I missed it somehow. I'll check and let you know :)

**Comment by StevenWuzz** [comment]
@JoelWiebe I've just resolved it. Do you still want the title to be turned into a hyperlink? That will be a very quick adjustment anyway.

**Comment by JoelWiebe** [comment]
@StevenWuzz Sure, let's throw in hyperlinks for titles just in case. Thanks!

**Pull request merged**
