### PR TITLE
ISSUE-287: Change to upvotes (dot-voting)

### LINKED ISSUE #287: Replace "likes" with dot-voting ("upvotes")
I'm thinking about replacing upvotes with dot-voting/sticker-voting (from design thinking). Rather than having students "like" a post because it does something for them emotionally, students could each have a set number of dots (e.g., 5) to upvote the best idea on a board. A single post could receive no vote, one vote, or multiple votes -- but the student only as a set number of votes (e.g. 5) that they can use on an entire board.

### PR DESCRIPTION
**Pull request by Ammar-T**
## Details

- Renamed all instances of "likes" to "upvotes"
- Changed thumbs up icons to upvote icons (not the best looking icons but the only ones available 🤷)
- Adds dot-voting (maximum # of upvotes given to each user)

Closes #287

### CODE REVIEW

**Review by l3n0ire — DISMISSED** [review]
Code looks good and passes manual testing. [testing doc](https://docs.google.com/spreadsheets/d/1KS1-TX2aYhLV4QUpNqHc2kCqoF5S_gOQ-ilWNS9AXvM/edit#gid=2025481591)

I think we should change the upvote icon on the fabric post or make the upvote area bigger. Clicking in btw the upvote icon and number is little awkward. 

If the teacher sets the max upvote count to a lower value (ex from 100 to 10),  the existing votes would remain. Students will have to find the posts they've upvoted and undo those upvotes, in order to upvote a new post. Maybe we can have a button to reset the upvotes for a board?

**Comment by Ammar-T** [comment]
@l3n0ire hey, sorry I should've tagged this with "in progress". 

I'm almost done adding the ability to add multiple upvotes per post for a user. Also changed up the icons to some nicer ones and fixed the positioning as well so the click space is accurate.

Also the remaining upvote counter is also in progress you can check out our conversation in the respective issue where we talked about this.

Good point on the last comment. Let's see what Joel says regarding a way to reset votes.

**Comment by l3n0ire** [comment]
@Ammar-T I noticed a bug with upvotes remaining. 

Steps to reproduce
- create a bucket-only post. 
- upvote it then undo those upvotes until you can't undo anymore.
- create a post on the board. upvote that post a few times. 
- the votes remaining becomes negative
- refreshing page fixes it and the upvotes are correct

Might be a synchronization issue with upvote count and bucket post?

**Comment by Ammar-T** [comment]
@l3n0ire Nice catch - fixed it!

Also didn't realize that the upvote counter should be updated if the post is deleted (i.e. those upvotes should be given back to the original upvoters). Fixed this as well!

**Comment by l3n0ire** [comment]
@Ammar-T  
when a bucketonly post is moved to the board the upvote count is 0. Refreshing it fixes it, so just sync issue. 
when the teach updates the max upvotes and a student continues to upvote at the same time, the count becomes negative. Refreshing the page also fixes this.

**Comment by JoelWiebe** [comment]
Brilliant work Ammar and fantastic feedback Colin!

Just a few thoughts: 
- In the board config, could we (1) rename the label as "Max upvotes per student", (2) move this tool to its own row above "Initial Zoom", and (3) as with dot-voting it is typical to have only about 5 votes to select the best ideas maybe we can change the max to 10 upvotes (as any more than that makes it overwhelming to select the top ideas)
- For some reason my local version is out of date (only has single upvotes) so the following suggestions my be out of date... what do you think of the following interface for up/down votes using the [material arrow icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aarrow_drop_up%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048) 
Screen Shot 2022-06-22 at 4 15 18 PM

Screen Shot 2022-06-22 at 4 15 36 PM 
(see [mockups here](https://docs.google.com/presentation/d/118u-hb44wZcG45fduaKBaW3LpDiuhqrB/edit#slide=id.g134a50750d9_0_33))

- Could we also change the icon from the four-arrow mouse pointer to a regular mouse pointer when hovering over the up/down vote icons on the card on the canvas?

**Comment by Ammar-T** [comment]
@JoelWiebe Thanks for the suggestions, I'll add those in now.

> For some reason my local version is out of date (only has single upvotes) so the following suggestions my be out of date... what do you think of the following interface for up/down votes using the [material arrow icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aarrow_drop_up%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)

Can you try doing `git pull origin issue-287` inside the branch? I've added new upvote/downvote icons so let me know what you think of those.

**Comment by Ammar-T** [comment]
@l3n0ire Fixed 1 of the issues but 

> when a bucketonly post is moved to the board the upvote count is 0. Refreshing it fixes it, so just sync issue.

I wasn't able to reproduce this. When I moved a bucket only post to the board, the counter didn't change.

**Comment by l3n0ire** [comment]
> @l3n0ire Fixed 1 of the issues but
> 
> > when a bucketonly post is moved to the board the upvote count is 0. Refreshing it fixes it, so just sync issue.
> 
> I wasn't able to reproduce this. When I moved a bucket only post to the board, the counter didn't change.

image
image
I gave 5 upvotes to the bucket post, then moved it to the board. The post on the board has 0 upvotes but should be 5 like the bucket post. refreshing the page fixes it.

**Comment by Ammar-T** [comment]
Ah I see what you mean, fixed it

**Comment by JoelWiebe** [comment]
> Added all of your suggestions Joel. I'll move the greying-out vote buttons and changing the cursor on vote hovering to a separate issue since it's a bit more work.

Sorry, just saw this. I can move these to new issues for others to work on.

**Comment by JoelWiebe** [comment]
@Ammar-T actually, could you just fix that one bug then merge this? We need to get you back to working on other cutting-edge stuff :)

**Comment by Ammar-T** [comment]
@JoelWiebe Hahaha yeah sure! 

I'll finish this up later today and continue on the task workflow stuff. I was just waiting on the backend additions from Zarif but I can just pull his branch with what he has now and start the integration.

**Pull request merged**
