### PR TITLE
ISSUE-376: Engagement Model for Class + Individual Students

### LINKED ISSUE #376: Create "Learner Model" UI for Engagement
The Learner Model UI will be added as part of the CK Monitor UI to display graphs of student data (some data manually entered by the teacher and some gathered from the CK Board).

The student and the teacher will each have access to the CK Monitor that includes the Learner Model UI (available as a button from any board canvas within a project), but the Learner Model will display differently for teachers and students.

1. The learner model will be added to the CK Monitor.
2. For the teacher, the heading "Learner Models" can be added below the task monitoring tools
Screen Shot 2022-10-12 at 11 29 13 PM

 - Selecting "View by Engagement" will open up a graph that shows a graph of all students' scores by that metric
 - A select control should allow for toggling between "Diagnostic" and "Re-assessment" values

Screen Shot 2022-11-04 at 12 22 01 AM

 - Alternatively, clicking on a single student's name will show all graphs for that particular student (i.e., for now, just the Engagement Model -- others can be implemented later)

3. Each Learner Model view should contain a gear in the top right corner which opens an editing screen for editing the dimensions of the Engagement Model

Screen Shot 2022-11-04 at 12 27 29 AM

 - This allows dimensions to be (1) named and added to the model or (2) removed

4. To view or modify the data for each student, the teacher can select the student's name in the left pane.

 - Displayed data includes: Engagement - entered by the teacher in terms of (a) diagnostic and (b) re-assessment 
 - (Other graphs will be implemented in the future)
 - The legend should include (a) Diagnostic, (b) Re-assessment, (c) Avg student diagnostic, (d) Avg student re-assessment

5. When viewing the data for each individual student, a pencil icon should exist next to the settings gear in the top right of the Learner Model UI which allows for editing each student's data

Screen Shot 2022-11-04 at 12 39 56 AM

 - Clicking on the pencil opens the a modal pop-up for the teacher to enter the dimension values for the Engagement Model

Screen Shot 2022-11-04 at 12 41 56 AM

 - The modal pop-up opens to the current student whose data was being viewed
 - The teacher also has access to a drop down that allows them to edit the data of other students
 - There are also two sets of data for each student: "Diagnostic" and "Re-assessment"

### Resources and recommendations

Please send me a PR early so I can review at each major step

**Important:** To see demo code of the javascript that I used to create the visualizations shown above or to explore other interactive demos, please explore the resources below:

- [Highcharts demo code.zip](https://github.com/encorelab/ck-board/files/9770363/Highcharts.demo.code.zip)
- https://www.highcharts.com/demo/polar
- https://www.highcharts.com/demo/gauge-activity

### PR DESCRIPTION
**Pull request by Ammar-T**
## Details

- First draft of the new engagement learner model
- Still loads of refactoring/cleanup needed but wanted to throw this out for initial thoughts

TODO
- [x] Create dimension values for students joining an already existing project
- [x] Move out learner model code from CK Monitor component into its own Angular component
- [x] Create personal student engagement graph (currently just a whole class engagement graph)
- [x] Pre-fill modal data if teacher edits dimensions for specific student (fill in student input and assessment by default)

Running:
- Remember to run npm installs in both frontend and backend

Closes #376

### CODE REVIEW

**Review by JoelWiebe — COMMENTED** [review]
Great work!

Suggestions:

- [x] Rename “Edit Chart” to “Edit Model”

Remaining tasks:
- [x] Add left pane heading for “View/Modify by Student” and a drop-down for selecting students; under this drop down add a “[Hide/View] Student Model]” button
- [x] Create a data model view for displaying individual student data (displayed when a students' name is selected and “View Student Model” button is clicked)
- [x] This individual student data model includes data for diagnostic, re-assessment, avg student diagnostic, and avg student re-assessment 
- [x] Selecting the Edit Model option in the top right corner of the chart opens up data editing for the current student

**Comment by Ammar-T** [comment]
@JoelWiebe These last couple commits should've added everything suggested.

1. Student filtering is added although I placed the select button right under the diagnostic/reassessment filter for uniformity.
2. I wasn't quite sure what the purpose of the "[Hide/View] Student Model]" button so I'm not sure the current implementation is what you're exactly looking for. Let me know if anything needs to be changed in this regard.
3. The student specific graph is as described in the issue description.
4. Editing the model data when viewing a specific student's graph autofills the student input field in the modal. 
5. Changed 'Edit Chart' to 'Edit Model'.
6. Fixed an issue where you could view todos and models at the same time and they would awkwardly be placed above each other. Now, you can only view either todos or models at once.

**Comment by JoelWiebe** [comment]
@Ammar-T Those changes look great. 

- [ ] Can we combine the two select controls into one (as seen in the image below)?

Screenshot 2023-03-27 at 12 19 00 AM

**Review by JoelWiebe — APPROVED** [review]
LGTM -- feel free to merge!

**Comment by Ammar-T** [comment]
@JoelWiebe Will fix conflicts and merge once the multi model PR is ready!

**Pull request merged**
