### PR TITLE
Issue 329 - Project Deletion

### LINKED ISSUE #329: Project Deletion
Add a project deletion toggle (like the board deletion toggle shown below):

Screen Shot 2022-07-11 at 12 34 47 PM

### PR DESCRIPTION
**Pull request by zarifmahmud**
## Details

- Adds project deletion functionality to backend (remove projects and all of their subcontents)
- Teachers have access to project deletion button on each of their projects.

- Issue: I made the button look similar to the picture shown in the issue description, but like the picture, the button is further down than it should be, I'm not sure how to align it better with the project title yet.

Closes #329

### CODE REVIEW

**Comment by LunarFang416** [comment]
@zarifmahmud my bad for the unclarity in the issue. I already implemented the Board deletion and the edit/delete toggles , their PRs just need to be merged. Once i merged those you can integrate this with that since the toggle buttons etc are all good there. Again, my bad for not mentioning this in the issue.(it'll hopefully be easy to integrate it into that).

**Comment by JoelWiebe** [comment]
Looks good!

Tested:
- Teachers can delete boards
- Students cannot delete boards

A few suggestions/ideas:
1. Can we add a confirmation dialogue (as we are permanently deleting)? We do have one for deleting the boards too, right?
2. For moving up the toggle button, what kind of options do we have @LunarFang416 @zarifmahmud? It looks like we need to overwrite two properties of the mat-icon-button class 
.mat-icon-button {
    height: 25px
    line-height: 20px
}

**Comment by LunarFang416** [comment]
@JoelWiebe i fixed the toggle styling in #319 since i was working on the toggles for the board initially. So @zarifmahmud you dont have to worry about the styling 👍 .
Screen Shot 2022-07-14 at 7 38 05 PM

**Comment by JoelWiebe** [comment]
@LunarFang416 Wonderful!!

@zarifmahmud then I think just the confirmation dialogue, then we should be good!

We could make this dialogue the same as for boards but just swap "board" with "project" in the text:
Screen Shot 2022-07-15 at 11 10 51 AM

**Comment by JoelWiebe** [comment]
@LunarFang416 Would you mind taking over this PR?

**Comment by LunarFang416** [comment]
@JoelWiebe Since this feature is closely linked with #319 i'll merge this branch into that branch so that it is easier for me to make sure the deletion is working fine. I'll close the PR so that you can just review #319 which will have this merged in it.

**Pull request closed without merging**
