### PR TITLE
Websockets + MongoDB Transition

### PR DESCRIPTION
**Pull request by Ammar-T**
TODO:
- [x] Fix merge conflicts
- [x] Update Heroku config to work with new backend

### CODE REVIEW

**Comment by JoelWiebe** [comment]
Wowsers!! Lots of changes!

Are these ready for testing? Is there anything still on firebase at this point or should I do a full test of creating, moving, editing, tagging, commenting, upvoting, etc.?

What does this mean for AZURE? Should we request an AZURE mongoDB instead of tying in the Firebase database (as I assume it may be difficult to migrate users later)?

Great work!

**Comment by Ammar-T** [comment]
Hey, yeah a complete re-haul at this point 😄.

I would wait a little bit to start testing just in case there's bugs due to it not being fully implemented yet. I'll let you know when everything's ready!

Good question on the azure integration. I think it would just be adding in some new environment variables (and removing old ones) since we're still just running on Node. 

Other than that there'll also be some extra configuration needed since now our frontend will need to communicate with the backend.

**Comment by Ammar-T** [comment]
@JoelWiebe This PR's ready for testing 🚀. There are some extra steps to setup/run the app now since there's a separate backend. I've added those into our Google Drive [here](https://docs.google.com/document/d/1HZU580D3U_GtDuL7IneSLLSH6-aAf-0C5eNsdmcoH24/edit).

@l3n0ire @DCH25 PR's ready for review as well, although since there's a lot of changes/additions it'll make more sense for me to go over it in a call. If that's okay with you 2, are there any days/times you would prefer?

**Comment by JoelWiebe** [comment]
@Ammar-T Brilliant!! That's really neat how you separated out the backend and the environment variable can be set on remote servers and dev machines. Thanks for all your work. I'll take a look soon!

**Comment by Ammar-T** [comment]
Fixed all merge conflicts!

**Comment by l3n0ire** [comment]
@encorelab/score-dev We can keep track of testing in this [document](https://docs.google.com/spreadsheets/d/1KS1-TX2aYhLV4QUpNqHc2kCqoF5S_gOQ-ilWNS9AXvM/edit#gid=1913009351)

**Comment by l3n0ire** [comment]
@Ammar-T I noticed that background images aren't filling the canvas properly (more details in testing document). Lmk if you're able to reproduce this issue. Seems to be a frontend only issue

**Comment by Ammar-T** [comment]
@l3n0ire Fixed it! The `imgSettings` field was spelled differently in the backend image settings model lol which is why the settings were never saved.

**Comment by Ammar-T** [comment]
@encorelab/score-dev You can test everything through the staging environment now since it has the new changes.

**Comment by l3n0ire** [comment]
> @l3n0ire Fixed it! The `imgSettings` field was spelled differently in the backend image settings model lol which is why the settings were never saved.
@Ammar-T 
Uploading the background image from board config works, but uploading bg image when creating board still has the same scaling issue.
Initial zoom only updates when the page is refreshed, not when "update configuration" is clicked

**Comment by l3n0ire** [comment]
@Ammar-T 
I found some more bugs with buckets including one nasty one 😬

**Comment by l3n0ire** [comment]
Retested. Bucket issues are fixed. Some bugs with permissions and background image scaling on board creation. Everything else looks good!

**Comment by Ammar-T** [comment]
@l3n0ire Fixed all of those as well now

**Comment by l3n0ire** [comment]
Still an issue with student moving post permission. Other bugs fixed.

**Comment by Ammar-T** [comment]
Should be everything now.

**Review by l3n0ire — APPROVED** [review]
Looks good. Feel free to merge.

**Comment by JoelWiebe** [comment]
@Ammar-T Great work knocking out all those fixes. Thanks for taking care of the users notified by own actions bug too.

**Pull request merged**
