### PR TITLE
Todo List PR Draft

### LINKED ISSUE #338: Create TODO List
- A Personal TODO List can be added to the Task Workspace UI
- There is one Personal TODO List per project
- Each student creates their own personal TODO list items

A TODO list item is typically about something to be completed outside of CK (e.g., ask tutor a question, talk to teacher about test prep, make study notes, etc.). Each TODO list item contains two elements:
- name
- deadline (date and time)

A TODO item is completed by simply clicking the corresponding checkbox. When the item is completed, a confetti animation is displayed with celebratory sound as reward/celebration. 

If the item is not yet completed as the deadline approaches, each student will receive a reminder of their approaching TODO item using the CK notifications tool (i.e., the student receives a notification the day before and on the day that it is due)

Once this feature is implemented, we can think about or explore ways of keeping track of completed items (maybe using trace logs for post study research analysis and UI such as timeline/graph visualizations for students to self-reflect on their progress in realtime)

### PR DESCRIPTION
**Pull request by LunarFang416**
## Details

- Added Todo List functionality which can be seen on the students project dashboard (separate for all projects a user is a part of)
- Todo Item icon is in the navbar of each project a student is in
- Confetti and a celebration sound effect is played when one or more todo items are completed
- Students can Edit/Delete existing todo items 

Work in Progress:
- Still working on the notifications for pending todo items, and overdue todo items; in the meantime other functionality of the todo list feature can be tested

Please let me know if there are bugs you encounter or any improvements/additions I can make to this feature. Thanks

Closes #338

### CODE REVIEW

**Comment by JoelWiebe** [comment]
I love this!! Haha

Animation
1. Can we customize the confetti? I think it would be funny if there would just be one confetti animation that begins exactly on the last drum kick noise in the music (one of the last noises is a thud, that could be the used as the sound for the confetti launching, haha)

Visualizing data
2. Could we have some kind of a "Completed Items" list -- so students can see a list of all the things they've accomplished?
3. Just out of curiosity, how hard would it be to additionally view these items in a calendar (even just a view only calendar) to see how these tasks space out throughout their year?
4. Might there be a way for teachers to view the TODO list from each student

Icons
5. Can we add the icon for this tool to each of the boards for the project as well (so they are consistently available)?
6. @Ammar-T should we do an icon shuffle (noticing that the listview icon is very similar to the TODO list (i.e., assign TODO list icon to listview; assign workspace icon to TODO list; assign a new icon to workspace -- maybe the "work" icon that looks like a briefcase)?

Wording
7. For clarity, can we change the label on the "Items Completed" button to something like "Mark as Completed"

Create new issue
8. Let's go forward without reminders for now... we can come back to that later (what's the blocking issue there... is it difficult to use the notifications tool, or is it just difficult to have it get triggered at a particular date & time)?

**Comment by LunarFang416** [comment]
@JoelWiebe 

> I love this!! Haha
> 
> Animation
> 
> 1. Can we customize the confetti? I think it would be funny if there would just be one confetti animation that begins exactly on the last drum kick noise in the music (one of the last noises is a thud, that could be the used as the sound for the confetti launching, haha)

Sure, that would be cool!

> 
> Visualizing data 
> 2. Could we have some kind of a "Completed Items" list -- so students can see a list of all the things they've accomplished? 

Sure, Ill add that.

>3. Just out of curiosity, how hard would it be to additionally view these items in a calendar (even just a view only calendar) to see how these tasks space out throughout their year? 

I found an angular calendar library online: https://github.com/mattlewis92/angular-calendar (preview: https://mattlewis92.github.io/angular-calendar/#/kitchen-sink) which is pretty neat, but it requires Angular 14.0 +, right now our project has Angular 12. @Ammar-T Could we upgrade t0 angular 14, or would that break stuff? Otherwise we wont be able to use the library. 

> 4. Might there be a way for teachers to view the TODO list from each student

Will have to create a new modal view for the teacher for that. Will do that.

> Icons 
> 5. Can we add the icon for this tool to each of the boards for the project as well (so they are consistently available)? 

Yep, will do that. 

> 6. @Ammar-T should we do an icon shuffle (noticing that the listview icon is very similar to the TODO list (i.e., assign TODO list icon to listview; assign workspace icon to TODO list; assign a new icon to workspace -- maybe the "work" icon that looks like a briefcase)?

I found this icon which could be used for the todo list modal. What do you think?

Screen Shot 2022-08-21 at 11 02 55 AM


> Wording 
> 7. For clarity, can we change the label on the "Items Completed" button to something like "Mark as Completed"

Sure, will do.

> Create new issue 
> 8. Let's go forward without reminders for now... we can come back to that later (what's the blocking issue there... is it difficult to use the notifications tool, or is it just difficult to have it get triggered at a particular date & time)?

The notification tool itself is not the problem, its just the method of how we send the notifications to the user. I had an initial idea of always checking when a user logs in if there are any reminders that need to be sent, and also checking when ever a socket event is pinged by a user (since it indicates activity from the user). This was causing a few bugs where it would sometimes not send the Notification create event, and it would also cause circular import errors which wouldn't allow me to use the todoItemService in the userService and socketService components. I think I just need a bit more time to play around with the code and I think the basic logic I have will work, just needs some refining. Will continue to work on this as well. 

I'll go ahead with creating an issue for this as well.

**Comment by JoelWiebe** [comment]
That teacher modal view is great!! I like all your suggestions. 

- Could we change the mouse hover text for the teacher's "Members Todo List" button to say "View All Todo Lists"?
- I notice the teacher Todo Lists modal only opens from the dashboard and not the boards (could we fix this for boards)?
- Sorry if I'm beginning to sound obsessed about this effect, haha -- To promote confetti scarcity :) so that students really need to work for that confetti, could we have only a single confetti shoot (instead of four) and move the audio clip a fraction of a second sooner so it perfectly lines up with the last thud of the drum?

**Comment by LunarFang416** [comment]
@JoelWiebe I had a few questions about the teacher being able to view the todo list modal of all members in a project.

Right now it is basically the same as what a student would see on their end. Do you want to keep it that way?
Also, when a teacher marks a students task completed by herself, do you still want it to shoot confetti or do you want to disable that?

**Comment by JoelWiebe** [comment]
> @JoelWiebe I had a few questions about the teacher being able to view the todo list modal of all members in a project.
> 
> Right now it is basically the same as what a student would see on their end. Do you want to keep it that way? Also, when a teacher marks a students task completed by herself, do you still want it to shoot confetti or do you want to disable that?

@LunarFang416 Yes, I like your current implementation. Great work!

**Review by JoelWiebe — APPROVED** [review]
Sorry, THIS was the one I meant to approve, haha. Really great work! Love this!

**Comment by JoelWiebe** [comment]
@DCH25 Would you mind reviewing this so we can merge it in maybe someday today?

**Comment by DCH25** [comment]
- When deleting from a todo-list with a single todo-item, the list will not update right away (needs to close and reopen the modal or add and delete another todo-item).
- Same bug occurs when deleting from a modal that has existing todo-items

**Comment by DCH25** [comment]
Try to avoid inline styling if you're using it in multiple instances.

Some examples: 

https://github.com/encorelab/ck-board/blob/4bb940c281c6e25809c048a3da213c42d8679a93/frontend/src/app/components/todo-list-modal/todo-list-modal.component.html#L5

https://github.com/encorelab/ck-board/blob/4bb940c281c6e25809c048a3da213c42d8679a93/frontend/src/app/components/todo-list-modal/todo-list-modal.component.html#L76

https://github.com/encorelab/ck-board/blob/4bb940c281c6e25809c048a3da213c42d8679a93/frontend/src/app/components/todo-list-modal/todo-list-modal.component.html#L49-L61

**Review by DCH25 — CHANGES_REQUESTED** [review]
Some minor bugs and styling issues (see my previous comments). Otherwise LGTM!

**Comment by LunarFang416** [comment]
> * When deleting from a todo-list with a single todo-item, the list will not update right away (needs to close and reopen the modal or add and delete another todo-item).
> * Same bug occurs when deleting from a modal that has existing todo-items

I'm trying to recreate this, but its working fine on my end.

**Comment by JoelWiebe** [comment]
@LunarFang416 @DCH25 Interesting, I seem to be noticing some errors now too.

To recreate bugs
 1. Each time I create a new todo item I now seem to be getting the following error in my console
 2. For the delete bug, it is inconsistent, but this is how I most often bot the bug. If I create a few new TODO items, then keeping the modal open I start deleting the posts starting with the items at the top of the list then sometimes the top item from the list does not delete right away. (Perhaps this is related to the generation of the error during creation?)

`NOTIFICATION_CREATE
(node:12600) UnhandledPromiseRejectionWarning: Error: {
 "errors": {
  "projectID": {
   "name": "ValidatorError",
   "message": "Path `projectID` is required.",
   "properties": {
    "message": "Path `projectID` is required.",
    "type": "required",
    "path": "projectID"
   },
   "kind": "required",
   "path": "projectID"
  },
  "viewed": {
   "name": "ValidatorError",
   "message": "Path `viewed` is required.",
   "properties": {
    "message": "Path `viewed` is required.",
    "type": "required",
    "path": "viewed"
   },
   "kind": "required",
   "path": "viewed"
  },
  "text": {
   "name": "ValidatorError",
   "message": "Path `text` is required.",
   "properties": {
    "message": "Path `text` is required.",
    "type": "required",
    "path": "text"
   },
   "kind": "required",
   "path": "text"
  },
  "type": {
   "name": "ValidatorError",
   "message": "Path `type` is required.",
   "properties": {
    "message": "Path `type` is required.",
    "type": "required",
    "path": "type"
   },
   "kind": "required",
   "path": "type"
  },
  "userID": {
   "name": "ValidatorError",
   "message": "Path `userID` is required.",
   "properties": {
    "message": "Path `userID` is required.",
    "type": "required",
    "path": "userID"
   },
   "kind": "required",
   "path": "userID"
  },
  "notificationID": {
   "name": "ValidatorError",
   "message": "Path `notificationID` is required.",
   "properties": {
    "message": "Path `notificationID` is required.",
    "type": "required",
    "path": "notificationID"
   },
   "kind": "required",
   "path": "notificationID"
  }
 },
 "_message": "ProjectNotificationModel validation failed",
 "name": "ValidationError",
 "message": "ProjectNotificationModel validation failed: projectID: Path `projectID` is required., viewed: Path `viewed` is required., text: Path `text` is required., type: Path `type` is required., userID: Path `userID` is required., notificationID: Path `notificationID` is required."
}
    at /Users/joelwiebe/ck-board/backend/src/repository/dalNotification.ts:48:11
    at Generator.throw (<anonymous>)
    at rejected (/Users/joelwiebe/ck-board/backend/src/repository/dalNotification.ts:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:12600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)`

**Comment by LunarFang416** [comment]
@JoelWiebe Just made some quick changes. Hopefully the problem doesn't occur again

**Comment by JoelWiebe** [comment]
Thanks @LunarFang416 !! This seems to be working for me 👍 

@DCH25, is this working on your end too?

**Review by DCH25 — APPROVED** [review]

**Comment by DCH25** [comment]
> Thanks @LunarFang416 !! This seems to be working for me 👍
> 
> @DCH25, is this working on your end too?

Yep working on my end too!

**Comment by LunarFang416** [comment]
@JoelWiebe Thanks for double checking. Is this good to go and merge? 👍

**Comment by JoelWiebe** [comment]
@LunarFang416 Yes, good to merge :)

**Pull request merged**
