### PR TITLE
Edit/Delete toggles for Board/Project Cards

### LINKED ISSUE #144: Dashboard card modifications
For boards, can we add the task title to the card as subtext?

Also for each card (both project and card) add a 3 dot menu for Edit and Delete?
image

Edit would open the same menu as the Adjust Settings button (but without needing to open the project or board).

For delete, perhaps we can have a confirmation dialogue box. If possible, maybe we can have a garbage bin where these can be recovered from.

### PR DESCRIPTION
**Pull request by LunarFang416**
## Details

- Edit/Delete toggle created for Boards in projects
- Edit toggle created for projects. Delete project has not been implemented yet so I did not include an option for that
- Changed existing functions slightly to cater the changes in project/board name changes so they can update on the dashboard
- Some images:
Screen Shot 2022-07-07 at 9 05 35 PM    Screen Shot 2022-07-07 at 9 05 52 PM
Screen Shot 2022-07-07 at 9 05 40 PM   Screen Shot 2022-07-07 at 9 05 46 PM

Closes #144 #329

### CODE REVIEW

**Comment by LunarFang416** [comment]
@JoelWiebe Do you want to have a delete project toggle as well (like the one for the board), or do you want to leave the toggles as they are right now?

**Comment by JoelWiebe** [comment]
Great work on this!

A few suggestions/ideas:
- Can we nudge the 3 dots up about 10 pixels so they line up with the title of the board/project?
- For changing the title on the project, for some reason the project title does not update immediately the first time but, if I edit the title a second or third time then the project title updates immediately
- If project deletion is quick, let's add it otherwise we can move you onto some other new developments :)

**Comment by DCH25** [comment]
Sometimes deleting a board results in the below image. I'm thinking the boards field in project isn't getting properly updated, but I'm not entirely sure what causes it since I've only been able to successfully reproduce the bug twice. 

image

**Comment by LunarFang416** [comment]
@JoelWiebe Just made the layout fixes and some changes in the code and i think now you wont have the problem where the project name does not update in some cases. For project deletion, for now ill create an issue for it and later on me or someone else can address the issue, if thats fine with you.

**Comment by JoelWiebe** [comment]
@LunarFang416 Creating project deletion as a separate issue sounds good to me. I can do that now if it hasn't been done already. For the time being, it's a low priority item so I'm fine if that waits.

For the board names, for some reason I'm still getting the same issue (with no name) but that's okay as long as it works on new boards. Maybe at some point we can go in the database and clean out the orphaned boards or add IDs to projects that don't have any if that's a quick item -- but no stress. Important thing is that new boards seem to work!

**Comment by Ammar-T** [comment]
@LunarFang416 @JoelWiebe Are we going to restrict editing/deleting boards to only teachers?

Based on code, I don't think we're doing that right? I may be wrong. But I strongly think students should not be able to delete projects/boards from the 3-dot menus.

**Comment by LunarFang416** [comment]
@Ammar-T Totally forgot about that lol. Ill get that sorted out. Thanks for letting me know👍

**Comment by JoelWiebe** [comment]
@LunarFang416 I may have found some kind of bug:

Tested:
1. Create a board called Board 2
2. Delete the board called Board 2
3. Create a new board called Board 2 (this seems to work if any board name is used here)
-> We get the picture in picture error
-> Project configuration dialogue is also broken

Screen Shot 2022-07-15 at 11 03 52 AM

**Comment by Ammar-T** [comment]
> @LunarFang416 I may have found some kind of bug:
> 
> Tested:
> 
> 1. Create a board called Board 2
> 2. Delete the board called Board 2
> 3. Create a new board called Board 2 (this seems to work if any board name is used here)
>    -> We get the picture in picture error
>    -> Project configuration dialogue is also broken
> 
> Screen Shot 2022-07-15 at 11 03 52 AM

@LunarFang416 Any update on this issue?

**Review by JoelWiebe — APPROVED** [review]
@LunarFang416 Thanks!!

**Review by Ammar-T — APPROVED** [review]
👍

**Pull request merged**
