### PR TITLE
CK Monitor UI 

### LINKED ISSUE #374: Create "CK Monitor" UI
The teacher needs a means of monitoring the progress of students on tasks

1. For this we can duplicate CK Workspace UI to create an additional UI, the CK Monitor (maybe use the [heart rate icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Amonitor_heart%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048))  -- this should only be visible to the teacher from each board view. (In the rare scenario that the teacher may also be assigned a task, I would continue to leave the icon for the "CK Workspace" available to the teacher as well).

2. We can rename CK Workspace in the nav bar to CK Monitor

3. On the left panel of the CK Monitor UI, the teacher can see a full list of all tasks. To monitor the task, they click the "Monitor Task" button next to a particular task.
Screen Shot 2022-10-11 at 3 37 46 PM

4. Once viewing the task, they can see the "Max Progress", "Avg Progress", and "Min Progress" displayed in the right side panel. This shows the progress of each group.
Screen Shot 2022-10-11 at 3 40 55 PM

5. In the middle of the canvas, the teacher can see each group, the members of the group, and the progress. This list should be sorted by progress (max progress on top and least progress on the bottom). This can be updated either in real-time or by polling every few seconds (e.g., 5 seconds).

### PR DESCRIPTION
**Pull request by LunarFang416**
## Details

- Implementation of the CK Monitor UI, similar in design to the workspace UI
- Updates Progress of Task in real time
- View of Monitoring Modal:

Screen Shot 2022-11-06 at 2 51 59 PM

Closes #374

### CODE REVIEW

**Comment by JoelWiebe** [comment]
Great work keeping the table up-to-date in real-time. It's really neat to see this in action!

Tested
- When creating a new task, the task shows up in CK Monitor
- Progress bar and table progress update in real-time
- Table displays appropriate groups, group members, and progress values

A few suggestions/questions:
 - For the CK Monitor icon, what do you think about swapping the timer icon with the [Monitoring icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Amonitoring%3AFILL%401%3Bwght%40700%3BGRAD%40200%3Bopsz%4048) -- perhaps with full weight to match the profile of other "filled" icons in the nav bar? 
 - On the left pane, could we (1) organize the tasks into the groupings (Pending Tasks, Active Tasks, and Completed Tasks) and (2) add the group name before the task name -- both of which the Workspace UI currently does?
Screen Shot 2022-11-07 at 12 12 12 AM

 - In the table, can we add a space after the comma for each group member (i.e., from "Abubukker,Ammar" to "Abubukker, "Ammar")
 - In the progress bar, could you add the 10px bottom margin to the Avg Progress bar as well?

**Comment by LunarFang416** [comment]
@JoelWiebe The reason why i didnt categorize the tasks between pending, active and completed is because, unlike the group tasks which we can see if a student has started/finished it, there is no direct way to see if a task workflow is complete/active/pending. One way we can do this, is check individually for each groupTask within a workflow, and if all grouptasks are completed we can categorize it as Completed, if None are completed then in Active, and if No group has started we can can classify the workflow as pending.

Does that sound good, or did you have something else in mind?

**Comment by JoelWiebe** [comment]
@LunarFang416 Thanks for the clarification! I think that's a great suggestion to mark a task as Pending if none have started, active once one has started, complete once all are completed, and (in line with the Workspace UI) we can also hide the tasks that have not yet been activated/enabled in the workflow management tool.

**Comment by JoelWiebe** [comment]
@LunarFang416 I also just updated the description above regarding group names. Rather than putting the group name(s) before the task name in the left pane, perhaps we can add to the group name(s) as a comma separated list below the task name (either above or below the task requirement).

**Review by JoelWiebe — CHANGES_REQUESTED** [review]
Tested
 - Tasks enter Pending category after they are activated
 - Tasks enter Active category after one group begins the task
 - Tasks enter Completed category after all groups complete the task
 - Group names appropriately displayed below each task

Ideas/suggestions:
1. Increase Activity Monitor weight to 700
Screen Shot 2022-11-11 at 7 56 56 PM

2. Change nav bar page name from "CK Workspace" to "CK Monitor"
Screen Shot 2022-11-11 at 7 58 18 PM

Thanks for all these changes, it is working great

**Review by JoelWiebe — APPROVED** [review]
Looks great!

**Comment by JoelWiebe** [comment]
@DCH25 Can you review this? I believe you will need this feature before building the learner model features

**Comment by JoelWiebe** [comment]
@DCH25 do you mind reviewing this one?

**Review by DCH25 — APPROVED** [review]
LGTM!

**Pull request merged**
