### PR TITLE
Add permission to hide buckets from students

### LINKED ISSUE #257: Permission to hide buckets from students
In board configuration settings, allow the teacher to hide the buckets. This would hide the bucket icon in the top navigation bar for students only.

### PR DESCRIPTION
**Pull request by DCH25**
## Details

- teachers can set the permission when adding a board or updating configuration

Closes #257

### CODE REVIEW

**Review by l3n0ire — APPROVED** [review]

**Comment by JoelWiebe** [comment]
@DCH25 Great work! Just a small additional request, would you mind adding headers to separate the permissions (e.g., Post Features, Anonymization, UI Elements)?

**Review by JoelWiebe — APPROVED** [review]
Tested
- Toggle show bucket permission while student has canvas open
- Toggle show bucket permission while no student has canvas open

Bucket icon shows/hides in real-time; great job!

**Comment by DCH25** [comment]
@JoelWiebe added the headers just as text, but I can also change them into dropdowns if that's preferrable

**Comment by JoelWiebe** [comment]
@zarifmahmud @LunarFang416 Would you mind reviewing when you get a chance?

**Pull request merged**
