### PR TITLE
Issue 229 manual adjust background image

### LINKED ISSUE #229: Add Manual Adjustment of Background Position/Size
Once a background picture has been uploaded, allow for manual adjustment of x and y offset and size from the Board Configurations.

This is particularly useful when using background organizers (Venn diagrams, boxes, labels, etc.) and need the image to be a particular size and center the screen on a particular item within the image.

image

Manual adjustment would should take place in the teacher's board configurations pop-up (where the background images are uploaded from).

### PR DESCRIPTION
**Pull request by DCH25**
## Details

- Added slider for background image size and input fields for the image's X, Y position to the board configuration modal
- Background image scale is rounded to the nearest integer to avoid long decimal places in the UI
- Board tab in board configuration is modified to match the updated UI in the mockups. Should this change also be applied to the add board modal as well? If so, should the background image features be included as well?

Closes #229

### CODE REVIEW

**Comment by JoelWiebe** [comment]
@DCH25 Great work! 
Testing:

1. Uploading and X, Y, and size adjustments work well
2. Can we have the X, Y, and size values show up immediately on background upload? Currently I need to close then re-open the board configurations to see the values
3. You are nicely rounding the X and Y values when adjusted; did we also want to round the original values that have trailing decimals?
Screen Shot 2022-08-20 at 9 06 49 AM
5. Should we only show X, Y, and size when a background exists, to simplify the modal when no background exists?
6. To reduce the visual overload, let's adjust the white space above/below the headers a bit (i.e., something like a margin of 20px 0 10px)

**Comment by JoelWiebe** [comment]
Can we delete the X, Y, and size values when a background image is remove rather than only when the background image is removed then the config modal is closed? 

Otherwise, if you delete the background image then immediately upload another background image and click Update Configuration it will apply the old X, Y, and size values to the newly uploaded background image.

**Comment by DCH25** [comment]
Only show background image settings when there is a background image. Show initial values (X, Y, Scale) on background image upload. Styling changes.

**Review by JoelWiebe — APPROVED** [review]
Fantastic work!!

**Comment by JoelWiebe** [comment]
@LunarFang416 Hey :) Would you have time to review this sometime today?

**Review by LunarFang416 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
