### PR TITLE
Fixed hardcoding dev/prod URLs and web socket port

### LINKED ISSUE #610: BUG: Avoid Hard-Coding Production URLs and Fix Web Sockets
### Bug
**Overview**
Replace all hard-coded production URLs and fix the incorrect web sockets port

### PR DESCRIPTION
**Pull request by JoelWiebe**
Used angular environment variables and backend .env file to avoid hardcoding dev and production URLs. Also, updated the web sockets port to fix port connection issue on production. 

## Details

- Test logging and navigating between pages to ensure new configurations are correct
- Check browser console while on canvas to ensure that no web socket errors appear

Closes #610

### CODE REVIEW

**Comment by JoelWiebe** [comment]
@markiianbabiak Can you please review this to ensure no more browser console web socket errors? If good, feel free to merge to develop, then create another pull request called Master <- Develop to merge into the master branch.

**Comment by markiianbabiak** [comment]
@JoelWiebe I get this error when trying to run the code CKBOARD_SERVER_ADDRESS environment variable not set.

**Comment by JoelWiebe** [comment]
@markiianbabiak Sorry, I had changed the README to include those instructions, but must have stashed that change with other changes before commiting. 

Please add this to your .env file:
CKBOARD_SERVER_ADDRESS="http://localhost:4201"

**Comment by JoelWiebe** [comment]
@markiianbabiak Please review as accepted if everything looks good.

Then, feel free to merge to develop, then create another pull request called Master <- Develop to merge into the master branch.

**Comment by markiianbabiak** [comment]
Tested creating the post and received an error in the console: `Access to XMLHttpRequest at 'http://localhost:8001/api/posts/' from origin 'http://localhost:4201' has been blocked by CORS policy: Request header field timeout is not allowed by Access-Control-Allow-Headers in preflight response.` Fixed it in the next commit. Afterwards, everything works smoothly.

**Comment by markiianbabiak** [comment]
@JoelWiebe Review my change and let me know if that's ok and I can proceed with merge

**Comment by JoelWiebe** [comment]
@markiianbabiak This looks good to me. Good catch! Let's go ahead with the merge :)

**Pull request merged**
